document.writeln("<div class=\'preloader\'>");
document.writeln("    <div class=\'lds-ripple\'>");
document.writeln("        <div>Enter Ego\'s Exit</div>");
document.writeln("        <div>Enter Ego\'s Exit</div>");
document.writeln("        <div>");
document.writeln("            <img src=\'assets/images/logo/logo_1.jpg\' height=\'100\' width=\'100\' alt=\'\' class=\'event-one__moc\'>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div><!-- /.preloader -->");
document.writeln("");
document.writeln("");
document.writeln("");