document.writeln("<div class=\'preloader\'>");
document.writeln("    <div class=\'lds-ripple\'>");
document.writeln("        <div>Enter Ego\'s Exit</div>");
document.writeln("        <div>Enter Ego\'s Exit</div>");
document.writeln("        <div>");
document.writeln("            <video width=\'143\' loop=\'loop\' autoplay=\'autoplay\' id=\'videoID4\'>");
document.writeln("                <source src=\'assets/images/logo.mp4\' type=\'video/mp4\'/>");
document.writeln("            </video>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div><!-- /.preloader -->");
document.writeln("");
document.writeln("");
document.writeln("");