document.writeln("<footer class=\'site-footer\'>");
document.writeln("    <div class=\'site-footer__bottom\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'inner-container\'>");
document.writeln("                <p>&copy; Copyright Yiyun Li. All Rights Reserved</p>");
document.writeln("                <a href=\'index.html\' class=\'site-footer__bottom-logo\'>");
document.writeln("                    <video width=\'50\' height=\'50\' loop=\'loop\' autoplay=\'autoplay\' id=\'videoID2\'>");
document.writeln("                        <source src=\'assets/images/logo.mp4\' type=\'video/mp4\'/>");
document.writeln("                    </video>");
document.writeln("                </a>");
document.writeln("                <div class=\'site-footer__bottom-links\'>");
document.writeln("                    <a href=\'#\'>Terms & conditions</a>");
document.writeln("                    <a href=\'#\'>Privacy policy & Terms of use</a>");
document.writeln("                </div><!-- /.site-footer__bottom-links -->");
document.writeln("            </div><!-- /.inner-container -->");
document.writeln("        </div><!-- /.container -->");
document.writeln("    </div><!-- /.site-footer__bottom -->");
document.writeln("</footer><!-- /.site-footer -->");
document.writeln("");