document.writeln("<nav class=\'main-nav-one stricky main-nav-one__home-three\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'inner-container\'>");
document.writeln("            <div class=\'logo-box\'>");
document.writeln("                <a href=\'index.html\'>");
document.writeln("                    <img src=\'assets/images/logo.GIF\' alt=\'\' width=\'143\'>");
document.writeln("<!--                    <video width=\'143\' loop=\'loop\' autoplay=\'autoplay\' id=\'videoID1\'>-->");
document.writeln("<!--                        <source src=\'assets/images/logo.mp4\' type=\'video/mp4\'/>-->");
document.writeln("<!--                    </video>-->");
document.writeln("                </a>");
document.writeln("                <a href=\'#\' class=\'side-menu__toggler\'><i class=\'muzex-icon-menu\'></i></a>");
document.writeln("            </div><!-- /.logo-box -->");
document.writeln("            <div class=\'main-nav__main-navigation\'>");
document.writeln("                <ul class=\'main-nav__navigation-box\'>");
document.writeln("                    <!--<li class=\'dropdown\'>-->");
document.writeln("<!--                    <li class=\'dropdown\'>-->");
document.writeln("                    <li><a href=\'\'>Home</a></li>");
document.writeln("                    <li><a href=\'event-3.html\'>Events</a></li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                        <a href=\'collection-fullwidth.html\'>Exhibitions</a>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'collection-fullwidth.html\'>All Exhibitions</a></li>");
document.writeln("                            <!--                                    <li><a href=\'collection-grid.html\'>Collections Grid</a></li>-->");
document.writeln("                            <li><a href=\'collection-masonary.html\'>Enter Ego\'s Exit</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li><a href=\'about.html\'>About Curator</a>");
document.writeln("                    </li>");
document.writeln("                    <li><a href=\'contact.html\'>Contact</a></li>");
document.writeln("                </ul><!-- /.main-nav__navigation-box -->");
document.writeln("            </div><!-- /.main-nav__main-navigation -->");
document.writeln("            <div class=\'main-nav__right\'>");
document.writeln("                <a class=\'sidemenu-icon side-content__toggler\' href=\'#\'><i class=\'muzex-icon-menu\'></i></a>");
document.writeln("            </div><!-- /.main-nav__right -->");
document.writeln("        </div><!-- /.inner-container -->");
document.writeln("    </div><!-- /.container -->");
document.writeln("</nav><!-- /.main-nav-one -->");
document.writeln("");