document.writeln("");
document.writeln("");
document.writeln("<div class=\'side-content__block\'>");
document.writeln("    <div class=\'side-content__block-overlay custom-cursor__overlay\'>");
document.writeln("        <div class=\'cursor\'></div>");
document.writeln("        <div class=\'cursor-follower\'></div>");
document.writeln("    </div><!-- /.side-content__block-overlay -->");
document.writeln("    <div class=\'side-content__block-inner \'>");
document.writeln("        <a href=\'index.html\'>");
document.writeln("            <img src=\'assets/images/logo.JPG\' alt=\'\' width=\'143\'>");
document.writeln("        </a>");
document.writeln("        <div class=\'side-content__block-about\'>");
document.writeln("            <h3 class=\'side-content__block__title\'>About Curator</h3><!-- /.side-content__block__title -->");
document.writeln("            <p class=\'side-content__block-about__text\'>Yiyun Li was born in 1994 in Anhui, China. Learned dance and painting since childhood. The undergraduate major is environmental art design, and the direction is exhibition design. Since 2019, she has been studying for a master\'s degree in Visual Art and Curatorial Studies at the New Academy of Fine Arts in Milan.");
document.writeln("            </p><!-- /.side-content__block-about__text -->");
document.writeln("            <a href=\'about.html\' class=\'thm-btn side-content__block-about__btn\'>More About Curator</a>");
document.writeln("        </div><!-- /.side-content__block-about -->");
document.writeln("        <hr class=\'side-content__block-line\'/>");
document.writeln("        <div class=\'side-content__block-contact\'>");
document.writeln("            <h3 class=\'side-content__block__title\'>Contact Me</h3><!-- /.side-content__block__title -->");
document.writeln("            <ul class=\'side-content__block-contact__list\'>");
document.writeln("                <li class=\'side-content__block-contact__list-item\'>");
document.writeln("                    <i class=\'fa fa-map-marker\'></i>");
document.writeln("                    NABA, Milan");
document.writeln("                </li><!-- /.side-content__block-contact__list-item -->");
document.writeln("<!--                <li class=\'side-content__block-contact__list-item\'>-->");
document.writeln("<!--                    <i class=\'fa fa-phone\'></i>-->");
document.writeln("<!--                    <a href=\'tel:\'>(526) 236-895-4732</a>-->");
document.writeln("<!--                </li>&lt;!&ndash; /.side-content__block-contact__list-item &ndash;&gt;-->");
document.writeln("                <li class=\'side-content__block-contact__list-item\'>");
document.writeln("                    <i class=\'fa fa-envelope\'></i>");
document.writeln("                    <a href=\'mailto:example@mail.com\'>li_yiyun@studenti.naba.it</a>");
document.writeln("                </li><!-- /.side-content__block-contact__list-item -->");
document.writeln("<!--                <li class=\'side-content__block-contact__list-item\'>-->");
document.writeln("<!--                    <i class=\'fa fa-clock\'></i>-->");
document.writeln("<!--                    Week Days: 09.00 to 18.00 Sunday: Closed-->");
document.writeln("<!--                </li>&lt;!&ndash; /.side-content__block-contact__list-item &ndash;&gt;-->");
document.writeln("            </ul><!-- /.side-content__block-contact__list -->");
document.writeln("        </div><!-- /.side-content__block-contact -->");
document.writeln("        <p class=\'side-content__block__text site-footer__copy-text\'><a href=\'\'");
document.writeln("                                                                       title=\'\'>Yiyun Li</a> <i");
document.writeln("                class=\'fa fa-copyright\'></i> 2020 All Right Reserved</p>");
document.writeln("    </div><!-- /.side-content__block-inner -->");
document.writeln("</div><!-- /.side-content__block -->");
document.writeln("");
document.writeln("<div class=\'side-menu__block\'>");
document.writeln("");
document.writeln("    <a href=\'#\' class=\'side-menu__toggler side-menu__close-btn\'><i class=\'fa fa-times\'></i>");
document.writeln("        <!-- /.fa fa-close --></a>");
document.writeln("");
document.writeln("    <div class=\'side-menu__block-overlay custom-cursor__overlay\'>");
document.writeln("        <div class=\'cursor\'></div>");
document.writeln("        <div class=\'cursor-follower\'></div>");
document.writeln("    </div><!-- /.side-menu__block-overlay -->");
document.writeln("    <div class=\'side-menu__block-inner \'>");
document.writeln("");
document.writeln("        <a href=\'index.html\' class=\'side-menu__logo\'><img src=\'assets/images/logo.JPG\' alt=\'\' width=\'143\'></a>");
document.writeln("        <nav class=\'mobile-nav__container\'>");
document.writeln("            <!-- content is loading via js -->");
document.writeln("        </nav>");
document.writeln("        <p class=\'side-menu__block__copy\'>(c) 2020 <a href=\'http://www.bootstrapmb.com\' title=\'\'>Muzex</a> - All rights");
document.writeln("            reserved.</p>");
document.writeln("        <div class=\'side-menu__social\'>");
document.writeln("            <a href=\'#\'><i class=\'fab fa-facebook-f\'></i></a>");
document.writeln("            <a href=\'#\'><i class=\'fab fa-google-plus\'></i></a>");
document.writeln("            <a href=\'#\'><i class=\'fab fa-twitter\'></i></a>");
document.writeln("            <a href=\'#\'><i class=\'fab fa-instagram\'></i></a>");
document.writeln("            <a href=\'#\'><i class=\'fab fa-pinterest-p\'></i></a>");
document.writeln("        </div>");
document.writeln("    </div><!-- /.side-menu__block-inner -->");
document.writeln("</div><!-- /.side-menu__block -->");