document.writeln("<a href=\'#\' data-target=\'html\' class=\'scroll-to-target scroll-to-top\'><i class=\'fa fa-angle-up\'></i></a>");
document.writeln("");
document.writeln("<!-- Template JS -->");
document.writeln("");
document.writeln("<script src=\'assets/js/jquery.min.js\'></script>");
document.writeln("<script src=\'assets/js/bootstrap.bundle.min.js\'></script>");
document.writeln("<script src=\'assets/js/bootstrap-datepicker.min.js\'></script>");
document.writeln("<script src=\'assets/js/bootstrap-select.min.js\'></script>");
document.writeln("<script src=\'assets/js/isotope.js\'></script>");
document.writeln("<script src=\'assets/js/jquery.ajaxchimp.min.js\'></script>");
document.writeln("<script src=\'assets/js/jquery.counterup.min.js\'></script>");
document.writeln("<script src=\'assets/js/jquery.magnific-popup.min.js\'></script>");
document.writeln("<script src=\'assets/js/jquery.mCustomScrollbar.concat.min.js\'></script>");
document.writeln("<script src=\'assets/js/jquery.validate.min.js\'></script>");
document.writeln("<script src=\'assets/js/owl.carousel.min.js\'></script>");
document.writeln("<script src=\'assets/js/TweenMax.min.js\'></script>");
document.writeln("<script src=\'assets/js/waypoints.min.js\'></script>");
document.writeln("<script src=\'assets/js/wow.min.js\'></script>");
document.writeln("<script src=\'assets/js/jquery.lettering.min.js\'></script>");
document.writeln("<script src=\'assets/js/jquery.circleType.js\'></script>");
document.writeln("");
document.writeln("<!-- Custom Scripts -->");
document.writeln("<script src=\'assets/js/theme.js\'></script>");
document.writeln("<!-- ending of global static 3: js files -->");
document.writeln("");
document.writeln("<script  type=\'text/javascript\' src=\'assets/js/play_video.js\'></script>");
document.writeln("");