document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("");
document.writeln("<!-- favicons -->");
document.writeln("<link rel=\'apple-touch-icon\' sizes=\'180x180\' href=\'assets/images/logo.JPG\'>");
document.writeln("<link rel=\'icon\' type=\'image/png\' sizes=\'32x32\' href=\'assets/images/logo.JPG\'>");
document.writeln("<link rel=\'icon\' type=\'image/png\' sizes=\'16x16\' href=\'assets/images/logo.JPG\'>");
document.writeln("<link rel=\'manifest\' href=\'assets/images/favicon/site.webmanifest\'>");
document.writeln("");
document.writeln("<!-- Fonts URL -->");
document.writeln("<link href=\'https://fonts.googleapis.com/css?family=Karla:400,700%7CPlayfair+Display:400,500,600,700,800,900%7CWork+Sans:300,400,500,600,700,800,900&display=swap\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("<!-- Plugins CSS -->");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/bootstrap.min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/bootstrap-datepicker.min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/bootstrap-select.min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/fontawesome-all.min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/jquery.mCustomScrollbar.min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/magnific-popup.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/owl.carousel.min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/owl.theme.default.min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/animate.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/hover-min.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/muzex-icons.css\'>");
document.writeln("");
document.writeln("<!-- Custom CSS -->");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/style.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'assets/css/responsive.css\'>");
// document.writeln("<script src=\'assets/js/pic_loop.js\'></script>");
document.writeln("");